name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for your issue! We appreciate your feedback and will look into it as soon as possible. Please make sure to include all necessary details (including a **minimal config** that can reproduce the error) to help us assist you better. Pull requests are also welcome!"
        pr-message: "Thank you for your pull request! We appreciate your contribution. Please ensure that your changes are well documented and tested, and are formatted as `noexpandtab`."
