name: panvimdoc

on:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: 'livepreview'
          pandoc: 'doc/livepreview.md'
          description: '*livepreview*'
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: 'livepreview-changelog'
          pandoc: 'doc/livepreview-changelog.md'
          description: '*livepreview-changelog*'


      - name: Commit and push documentation
        uses: ./.github/actions/commit-and-push
        with:
          commit-message: 'Update Vimdoc based on README'
          files: 'doc/*'
          github_token: ${{ secrets.GITHUB_TOKEN }}

